
<div class="container-fluid">
  <div class="col-xl-12 col-lg-12 col-md-12">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body ">
              <h1 class="h4 text-center text-gray-900 mb-4" style="font-size: 50px;font-weight: bold">Kelola  Pasien</h1>
                  <table class="table table-bordered"  id="dataTable">
                    <thead >
                        <tr>
                            <th style="width: 70px">NO</th>
                            <th colspan=""  class=" thLeftText">NO Rekam Medis</th>
                            <th colspan=""  class=" thLeftText">No Induk Kependudukan (NIK)</th>
                            <th colspan=""  class=" thLeftText">Nama Pasien</th>
                            <th colspan=""  class=" thLeftText">Tempat Lahir </th>
                            <th colspan=""  class=" thLeftText">Tanggal Lahir</th>
                            <th colspan=""  class=" thLeftText">Alamat</th>
                            <th colspan=""  class=" thLeftText">No Hp</th>
                            <th colspan=""  class=" thLeftText">Tanggal Pendaftaran</th>
                            <th colspan=""  class=" thLeftText">Action</th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
            </table>
        </div>
      </div>
  </div>
</div>


<div id="Editdata" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
      <h4 class="modal-title">Edit Data Pasien</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
      <form id="myForm" >
      
          <input type="hidden" id="id_pasien"  class="form-control" /></input>

             <div class="form-group">
                  <label> No Rekam Medis</label><br>
                  <input type="number" id="no_rekam_medis" placeholder="No Rekam Medis"  class="form-control" max="999999999999999" maxlength="8" disabled ></input>                    
              </div>
        
              <div class="form-group">
                  <label>No Induk Kependudukan (NIK)</label>
                  <input type="number" id="ktp" class="form-control" placeholder="No Induk Kependudukan (NIK)" max="9999999999999999" maxlength="16"></input>
              </div>

              <div class="form-group">
                  <label>Nama Pasien</label>
                  <input type="text" id="nama"  class="form-control"   placeholder="Nama Lengkap" ></input>
              </div>

              <div class="form-group ">
                  <label>Tempat Lahir</label>
                  <textarea  type="text" id="tempat_lahir"  class="form-control " placeholder="Tempat Lahir" ></textarea >
              </div>

              <div class="form-group">
                  <label>Tanggal Lahir</label>
                  <input type="date" id="tanggal_lahir"  class="form-control" /></input>
              </div>
              <div class="form-group" >
                  <label>Alamat</label>
                  <textarea  type="text" id="alamat" rows="3" class="form-control" placeholder="Alamat"/></textarea >
              </div>

              <div class="form-group">
                  <label>No HP</label>
                  <input type="number" id="no_hp"  class="form-control " placeholder="No Handphone" maxlength="13" /></input>
              </div>

                    
           
            <div class="modal-footer">
         <button  button type="button" class="btn btn-primary" id="edit">Edit</button>
         <button  button type="button" class="btn btn-danger" onclick="reset()">Reset</button>
        <button type="submit" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </form>
    </div>
    </div>

  </div>
</div>
