
    
<div class="container-fluid">
  <div class="col-xl-12 col-lg-12 col-md-12">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body ">
            <h1 class="h4 text-center text-gray-900 mb-4" style="font-size: 50px;font-weight: bold">Seluruh Data Jadwal Dokter </h1>  
              <br>
              <br>
              <table class="table table-bordered" id="dataTable">
                <thead>
                  <tr class="table-infos">
                        <th style="">NO</th>
                        <th >Nama Poli</th>
                        <th >Nama Dokter</th>
                        <th>Ruangan</th>
                        <th >Antrian Seluruh</th>
                        <th>Jam Mulai</th>
                        <th >Waktu Antrian</th>
                        <th >Tanggal Antrian</th>
                        <th >Action</th>
                  </tr>
                </thead>
                      <tbody id="tableregisterdokter" >
                      </tbody>
                  </table>
            
        </div>
      </div>
  </div>
</div>
