 <!-- breadcrumb start-->
 <hr>
  <hr>
  <hr>
  <hr>

 <section class="breadcrumb_part breadcrumb_bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner">
                        <div class="breadcrumb_iner_item">
                            <h2>Dokter</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb start-->

    <!--::doctor_part start::-->
    <section class="doctor_part single_page_doctor_part" style="padding:20px;">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-8" style="    height: 75px;  ">
                    <div class="section_tittle text-center">
                        <h2 >  Beberapa dokter di rumah sakit</h2>
                       
                    </div>
                </div>
            </div>

            <div class="row dokter">
               
            </div>
        </div>
    </section>
