<!-- breadcrumb start-->
<hr>
  <hr>
  <hr>
  <hr>

 <section class="breadcrumb_part breadcrumb_bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner">
                        <div class="breadcrumb_iner_item">
                            <h2>Poli</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb start-->

     <!-- feature_part start-->
     <section class="doctor_part single_page_doctor_part" style="padding:0px;" >
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-8">
                    <div class="section_tittle text-center">
                        <h2> Poli Kami </h2>
                    </div>
                </div>
            </div>

            <div class="row poli">
               
            </div>
        </div>
    </section>
    <!-- feature_part start-->
