<?= $this->doctype() ?>

<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Antrian </title>

      <!-- Custom fonts for this template-->
    <?= $this->headLink(['rel' => 'sylesheet', 'type' => 'text/css' , 'href' => $this->basePath() . '/tamplate/img/favicon.png'])
            ->prependStylesheet($this->basePath('/tamplateadmin/vendor/fontawesome-free/css/all.min.css'))
            ->prependStylesheet($this->basePath('/tamplateadmin/assets/css/colors.css'))
            ->prependStylesheet($this->basePath('/tamplateadmin/assets/css/bootstrap.css'))
            ->prependStylesheet($this->basePath('/tamplateadmin/assets/css/icons/icomoon/styles.css'))
            ->prependStylesheet($this->basePath('/tamplateadmin/assets/css/core.css'))
            ->prependStylesheet($this->basePath('/tamplateadmin/assets/css/components.css'))
            ->prependStylesheet($this->basePath('/tamplateadmin/vendor/datatables/dataTables.bootstrap4.min.css'))
            ->prependStylesheet($this->basePath('/tamplateadmin/css/sb-admin-2.min.css'))
            ->prependStylesheet($this->basePath('/css/dasboard.css'))
      ?>
  
      <script src="<?php $this->basePath();?>/tamplateadmin/vendor/jquery/jquery.min.js"></script>
      <script src="<?php $this->basePath();?>/tamplateadmin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
      <script src="<?php $this->basePath();?>/tamplateadmin/vendor/jquery-easing/jquery.easing.min.js"></script>
      <script src="<?php $this->basePath();?>/tamplateadmin/js/sb-admin-2.min.js"></script>
      <script src="<?php $this->basePath();?>/tamplateadmin/assets/js/core/libraries/jquery.min.js"></script>
      <script src="<?php $this->basePath();?>/tamplateadmin/assets/js/plugins/notifications/sweet_alert.min.js"></script>
      <script src="<?php $this->basePath();?>/tamplateadmin/vendor/datatables/jquery.dataTables.min.js"></script>
      <script src="<?php $this->basePath();?>/tamplateadmin/vendor/datatables/dataTables.bootstrap4.min.js"></script>
      <script src="<?php $this->basePath();?>/js/bootstrap.min.js"></script>
    </head>

    <style type='text/css'>
      .table{
      table-layout: fixed;
      word-wrap: break-word;
      }
    </style>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper" > 

  <!-- Sidebar -->
  <ul  class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
          <div class="sidebar-brand-text mx-3 " style="font-size: 12px" >Admin Antrian</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
      <a class="nav-link" href="<?php echo $this->basePath('admin/dasboard') ?>">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span style="font-size: 14px">Dashboard</span>
      </a>
      <hr class="sidebar-divider">
    </li>
  
 


    <!-- Heading -->
    <div class="sidebar-heading" style="font-size: 12px">
      Interface
    </div>

    
    <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="<?php echo $this->basePath('admin/antrianadmin') ?>">
          <i class="fas fa-fw fa-folder"></i>
          <span style="font-size: 11px" href="">Antrian</span>
        </a>
      </li> 
      <li class="nav-item">
        <a  class="nav-link collapsed" href="<?php echo $this->basePath('admin/registrasidokter') ?>">
          <i class="fas fa-fw fa-cog"></i>
          <span style="font-size: 11px" href="">Registrasi Dokter</span>
        </a>
        <hr class="sidebar-divider">
      </li> 

      <div class="sidebar-heading" style="font-size: 12px">
      Feature
      </div>
    
      
      <li class="nav-item">
        <a  class="nav-link collapsed" href="<?php echo $this->basePath('admin/kelolapasien') ?>">
          <i class="fas fa-fw fa-table"></i>
          <span style="font-size: 12px" href="">Kelola Antrian </span>
        </a>
      </li> 
      
      <li class="nav-item">
        <a  class="nav-link collapsed" href="<?php echo $this->basePath('admin/kelolapoli') ?>">
          <i class="fas fa-fw fa-table"></i>
          <span style="font-size: 12px" href="">Kelola Poli</span>
        </a>
      </li> 
      
      <li class="nav-item">
        <a  class="nav-link collapsed" href="<?php echo $this->basePath('admin/keloladokter') ?>">
          <i class="fas fa-fw fa-table"></i>
          <span style="font-size: 12px" href="">Kelola Dokter</span>
        </a>
      </li> 
      <li class="nav-item">
        <a  class="nav-link collapsed" href="<?php echo $this->basePath('admin/kelolaruangan') ?>">
          <i class="fas fa-fw fa-table"></i>
          <span style="font-size: 12px" href="">Kelola Ruangan</span>
        </a>
      </li> 
      <li class="nav-item">
        <a  class="nav-link collapsed" href="<?php echo $this->basePath('admin/cobain') ?>">
          <i class="fas fa-fw fa-table"></i>
          <span style="font-size: 12px" href="">Cobain</span>
        </a>
      </li> 

    
   </ul>
  <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">
    
        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="<?php echo $this->basePath('user/logout') ?>" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
              </a>
            </li>

          </ul>

        </nav>

     
    


<!-- End of Topbar -->
      <div class="content-wrapper">
                          <!-- Content area -->
          <div class="content">
             <?= $this->content ?>
          </div>
      </div>
                          
                
</div>
        <?= $this->headScript()
      ->prependFile($this->basePath('js/bootstrap.min.js'))
      ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
      ->prependFile($this->basePath('/tamplate/js/bootbox.all.min.js'))
      ->prependFile($this->basePath('js/jquery-clock-timepicker.min.js'))
			
    ?>
        <?= $this->inlineScript() ?>
    </body>
</html>
