
<div class="container-fluid">
  <div class="col-xl-12 col-lg-12 col-md-12">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body ">
              <h1 class="h4 text-center text-gray-900 mb-4" style="font-size: 50px;font-weight: bold">Antrian Terlewat</h1>
              <!-- <form class="form-inline">
            <div class="form-group form-control-lg ">
                <label >Pilih poli </label>
                <select name="nama_poli" id="poli" class="form-control" >
                <option  disabled selected>Pilih </option>
                </select> 
            </div>
            <div class="form-group form-control-lg">
                <label>Pilih dokter</label> <br>
                <select id="dokter" name="nama_dokter" class="form-control">
                <option disabled selected> Pilih </option>
                </select>
            </div>
            </form> -->
            <br>
                  <table class="table table-bordered"  id="dataTable">
                    <thead >
                        <tr>
                            <th style="width: 70px">NO</th>
                            <th colspan=""  class=" thLeftText">NO Antrian Pasien</th>
                            <th colspan=""  class=" thLeftText">Nama Pasien</th>
                            <th colspan=""  class=" thLeftText">Nama Dokter</th>
                            <th colspan=""  class=" thLeftText">Nama Poli</th>
                            <th colspan=""  class=" thLeftText">Status</th>
                            <th colspan=""  class=" thLeftText">Action</th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
            </table>
        </div>
      </div>
  </div>
</div>

